name: zombies
version: ${project.version}
main: io.github.zap.zombies.Zombies
api-version: 1.16
depend: [ arena-api, SlimeWorldManager, MythicMobs, ProtocolLib ]
commands:
  zap_debug:
    description: "ZAP debugging utility command."
