name: Zombies
version: ${project.version}
main: io.github.zap.zombies.Zombies
api-version: 1.16
depend: [ ArenaApi, SlimeWorldManager, MythicMobs ]
commands:
  zap:
    description: "Command used by this plugin."