name: Zombies
version: 1.0
main: io.github.zap.zombies.Zombies
api-version: 1.16
depend: [ ArenaApi, SlimeWorldManager ]
loadbefore: [ MythicMobs ]
commands:
  zap:
    description: "Generic command used by this plugin for various things."
  mapeditor:
    description: "Mapeditor command."
  pu:
    description: "ZZ"
