name: ZombiesPlugin
version: ${project.version}
main: io.github.zap.ZombiesPlugin
api-version: 1.16
authors: [ Steank, TachibanaYui, Lysogenic, syeyoung, Dictyophora ]
description: A better version of the Hypixel minigame Zombies.
loadbefore: [ MythicMobs ]
depend: [ SlimeWorldManager ]
commands:
  zap_debug:
    description: A debugging command.
    usage: /zap_debug for more info.