name: ZombiesPlugin
version: ${project.version}
main: io.github.zap.ZombiesPlugin
api-version: 1.16
authors: [ Steank, TachibanaYui, Lysogenic, syeyoung, Dictyophora ]
description: A better version of the Hypixel minigame Zombies.
loadbefore: [ MythicMobs ]
depend: [ SlimeWorldManager ]