name: PartyPlusPlus
version: ${version}
main: io.github.zap.party.plugin.PartyPlugin
author: thamid
api-version: 1.16
commands:
  party:
    description: "All party-related commands"
    aliases: [ p ]
